### ISSUE TITLE
Add a `version` command

### ISSUE THREAD

**Issue by SrRyan** [robherley/reb-bot#5]
Add a `version` command so that you can know what release is currently being used by the bot. 

Example input:  `!version`
Example output: `Currently using release v0.3.0`

Bonus points if you also include a upgrade hint if there is a newer version

**Comment by robherley** [comment]
added by a combo of
- https://github.com/robherley/reb-bot/commit/a751d7f8a2474929112a756abdf0c1a450130008
- https://github.com/robherley/reb-bot/commit/388ccf8e19702a7a29e19e85c9a44070182ad1ba

version is displayed in `/ping`
